### ISSUE TITLE
Remove $dbObj->Connect() codes in data and verify pages

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#20]
I had moved the Database::Connect() into constructor, so we don't need to call Connect() manually anymore. Please remove any Database::Connect() codes and its correspond checks.

**Comment by prophetyang** [comment]
data_check.php:$success = $dbObj->Connect();
data_delete.php:$success = $dbObj->Connect();
data_export.php:$success = $dbObj->Connect();
data_get.php:$success = $dbObj->Connect();
data_import_inshore.php:$success = $dbObj->Connect();
verify_association_inshore_data.php:            $success = $dbObj->Connect();
verify_association_inshore_data.php:                  $success = $dbObj->Connect();
verify_association_inshore_data.php:                  $success = $dbObj->Connect();
verify_get.php:$success = $dbObj->Connect();

**Comment by kindwind** [comment]
We don't have to use  $dbObj->Connect() to connect to database even the page does not include header.php. Hence, remove all of them.

Done~
