### ISSUE TITLE
Adjust page layout for data and verify pages

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#21]
We should keep the page layout as following:

1. include header.php
2. check permission
3. display submenu
4. page specific javascript
5. page codes

[Example: sys_association.php]
<?php
require_once('header.php');
if (! $userObj->m_permissionObj->hasSysPermission()) {
  $utilsObj->m_jsObj->popup_no_permission_message();
}
/* display submenu */
$utilsObj->m_menuObj->gen_sys_submenu();
?>

<script src="js/sys_fish_association.js"></script>

...

[Example: sys_association_helper.php (for those pages that don't need main menu and submenu)]
<?php
session_start();
date_default_timezone_set('Asia/Taipei');
require_once('includes/include.php');
header('Content-Type: text/html; charset=utf-8');
$loginObj = LoginInstance::GetInstance();
if (! $loginObj->loginCheck()) {
  return;
}
....

**Comment by kindwind** [comment]
Done~
