### ISSUE TITLE
Update the way to retrieve user object in data/verify pages

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#22]
User object is now stored in PHP session, thus, we have to unserialize it to get an user object. 
If this issue is done, please handle over to me, I will remove the redundant codes ($_SESSION['user_id'])

Example:
$userObj = ($_SESSION['userObj']) ? unserialize($_SESSION['userObj']) : ""; /* userObj could be null */

$user_id = $userObj->get_user_id();

**Comment by kindwind** [comment]
Done~

**Comment by prophetyang** [comment]
Please help to update the way to get userObj to the following format:
$userObj = ($_SESSION['userObj']) ? unserialize($_SESSION['userObj']) : "";

**Comment by kindwind** [comment]
Done~
