### ISSUE TITLE
document type query doesn't work in data_opensea.php

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#27]
If we choose all document types:
![image](https://cloud.githubusercontent.com/assets/15800151/12373316/7157d2ce-bcb0-11e5-92ec-8221dc77ab93.png)

No data entry is displayed if we choose one of the two document types
![image](https://cloud.githubusercontent.com/assets/15800151/12373319/958151c0-bcb0-11e5-8f8b-edba8b8ad29c.png)

**Comment by kindwind** [comment]
fixed! Done~
