### ISSUE TITLE
Doesn't reload when delete all entries is done at data_inshore.php

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#32]

**Comment by kindwind** [comment]
Should it be reload !?

**Comment by kindwind** [comment]
I will add reload !

**Comment by prophetyang** [comment]
The table doesn't update when I click delete all button. :(

**Comment by kindwind** [comment]
It is a bug XD

**Comment by prophetyang** [comment]
sure it is

**Comment by prophetyang** [comment]
![image](https://cloud.githubusercontent.com/assets/15800151/12437753/736a4846-bf5b-11e5-8d07-705d8d033ddb.png)

**Comment by prophetyang** [comment]
verified, close this issue.
