### ISSUE TITLE
Data import issue

### ISSUE THREAD

**Issue by prophetyang** [FantasticThought/tfsda#36]
There will be multiple data forms with the same serial number created when importing data excel files.

[before import]
![image](https://cloud.githubusercontent.com/assets/15800151/12585610/c012bd0a-c487-11e5-8eb7-6332d397e783.png)

[after import]
![image](https://cloud.githubusercontent.com/assets/15800151/12585613/c4d0d93a-c487-11e5-8a1b-d58e2aea5ccf.png)

**Comment by kindwind** [comment]
I will fix it~XD

**Comment by kindwind** [comment]
Done~ Please help to check it, thanks~

**Comment by kindwind** [comment]
wait for test

**Comment by prophetyang** [comment]
test done.
